---
name: Code style

"on":
  pull_request:
  push:
    branches:
      - main

jobs:
  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@v6

  yamllint:
    name: YAML Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install yamllint.
        run: pip3 install yamllint

      - name: Lint code.
        run: |
          yamllint .
